In [1]:
import pandas as pd
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
import numpy as np

In [2]:
train_df = pd.read_csv('../generated dataset/train.csv')
valid_df = pd.read_csv('../generated dataset/valid.csv')
test_df = pd.read_csv('../generated dataset/test.csv')

In [3]:
train_df.head(5)

Label                                              Image  Feature_0  \
0  Hibiscus  IMG_20241029_131633_jpg.rf.a3f2d7fa633ae0536e8...        0.0   
1  Hibiscus  IMG_20241029_131640_jpg.rf.30a12f9b36a51bb91c4...        0.0   
2  Hibiscus  IMG_20241029_131646_jpg.rf.c743c72ae1c3b403d16...        0.0   
3  Hibiscus  IMG_20241029_131651_jpg.rf.203f579e95e3f696a72...       24.0   
4  Hibiscus  IMG_20241029_131711_jpg.rf.c3aee7f34bec54a8830...        0.0   

   Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6  \
0        0.0        2.0        0.0        0.0        0.0        0.0   
1        0.0        0.0        0.0        0.0        0.0        0.0   
2        0.0        0.0        0.0       46.0      152.0        0.0   
3        3.0        0.0        0.0        0.0        0.0        4.0   
4        0.0        1.0      131.0       17.0        0.0        0.0   

   Feature_7  ...  Feature_12790  Feature_12791  Feature_12792  Feature_12793  \
0        0.0  ...           14.0           47.0           11.0            1.0   
1        0.0  ...          115.0           53.0          166.0            0.0   
2        0.0  ...            1.0           28.0            0.0            0.0   
3        6.0  ...            2.0            6.0           89.0           12.0   
4        0.0  ...            1.0           64.0            1.0            1.0   

   Feature_12794  Feature_12795  Feature_12796  Feature_12797  Feature_12798  \
0            0.0            0.0           56.0           66.0           16.0   
1            0.0            0.0            0.0            1.0            8.0   
2            1.0            1.0            1.0            1.0            0.0   
3            0.0            0.0          102.0          131.0            4.0   
4            1.0            0.0            0.0            0.0            1.0   

   Feature_12799  
0           12.0  
1          166.0  
2            0.0  
3            7.0  
4            3.0  

[5 rows x 12802 columns]

In [5]:
X_train, y_train = train_df.drop(columns=['Image', 'Label']), train_df['Label']
X_valid, y_valid = valid_df.drop(columns=['Image', 'Label']), valid_df['Label']
X_test, y_test = test_df.drop(columns=['Image', 'Label']), test_df['Label']

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_valid)
X_test = scaler.transform(X_test)

In [7]:
results = {}

Given a model it will evaluate with the help of the earlier dataset

In [8]:
def evaluate_model(name, model, X_train, y_train, X_valid, y_valid, X_test, y_test):
    print(f"\nTraining {name} model...")
    model.fit(X_train, y_train)

    y_valid_pred = model.predict(X_valid)
    print(f"\nValidation Performance of {name}:")
    print(confusion_matrix(y_valid, y_valid_pred))
    print(classification_report(y_valid, y_valid_pred))

    y_test_pred = model.predict(X_test)
    print(f"\nTest Performance of {name}:")
    print(confusion_matrix(y_test, y_test_pred))
    print(classification_report(y_test, y_test_pred))

### 1. Support Vector Machine

In [9]:
svm_model = SVC(kernel='linear', C=1)
evaluate_model("SVM", svm_model, X_train, y_train, X_valid, y_valid, X_test, y_test)


Training SVM model...

Validation Performance of SVM:
[[ 0  0  0  0  0  1  0  0  1  0]
 [ 0  1  0  0  0  0  0  4  4  0]
 [ 0  1  0  0  0  1  0  2  1  0]
 [ 0  1  0  0  0  0  0  0  1  0]
 [ 0  1  0  0  1  0  0  0  2  0]
 [ 1  0  0  0  0  1  0  0  1  0]
 [ 0  6  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  1  0  0  2  0  0]
 [ 0  0  1  3  0  0  0  0 57  0]
 [ 0  2  4  0  1  0  0  0  0  0]]
              precision    recall  f1-score   support

      Ajwain       0.00      0.00      0.00         2
      Almond       0.08      0.11      0.10         9
      Ashoka       0.00      0.00      0.00         5
   DrumStick       0.00      0.00      0.00         2
    Fittonia       0.33      0.25      0.29         4
    Hibiscus       0.33      0.33      0.33         3
   JackFruit       0.00      0.00      0.00         8
       Mango       0.20      0.67      0.31         3
        Neem       0.85      0.93      0.89        61
     Parijat       0.00      0.00      0.00         7

    accuracy      

e:\!VNIT College\A. Pattern Recognition\Leaf\venv\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
e:\!VNIT College\A. Pattern Recognition\Leaf\venv\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
e:\!VNIT College\A. Pattern Recognition\Leaf\venv\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metr

### 2. Parzen Window (Linear Classifier)

In [10]:
from sklearn.naive_bayes import GaussianNB
parzen_model = GaussianNB()
evaluate_model("Parzen Windows (Gaussian Naive Bayes)", parzen_model, X_train, y_train, X_valid, y_valid, X_test, y_test)



Training Parzen Windows (Gaussian Naive Bayes) model...

Validation Performance of Parzen Windows (Gaussian Naive Bayes):
[[ 0  2  0  0  0  0  0  0  0  0]
 [ 0  5  0  0  0  0  0  0  4  0]
 [ 0  3  0  0  1  0  0  0  1  0]
 [ 0  1  0  0  0  0  0  0  1  0]
 [ 0  2  0  0  1  0  0  0  1  0]
 [ 0  2  0  0  0  1  0  0  0  0]
 [ 0  8  0  0  0  0  0  0  0  0]
 [ 0  3  0  0  0  0  0  0  0  0]
 [ 0  5  0  1  4  0  0  0 51  0]
 [ 0  7  0  0  0  0  0  0  0  0]]
              precision    recall  f1-score   support

      Ajwain       0.00      0.00      0.00         2
      Almond       0.13      0.56      0.21         9
      Ashoka       0.00      0.00      0.00         5
   DrumStick       0.00      0.00      0.00         2
    Fittonia       0.17      0.25      0.20         4
    Hibiscus       1.00      0.33      0.50         3
   JackFruit       0.00      0.00      0.00         8
       Mango       0.00      0.00      0.00         3
        Neem       0.88      0.84      0.86        61
     

e:\!VNIT College\A. Pattern Recognition\Leaf\venv\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
e:\!VNIT College\A. Pattern Recognition\Leaf\venv\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
e:\!VNIT College\A. Pattern Recognition\Leaf\venv\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metr

### 3. k-Nearest Neighbor

In [11]:
knn_model = KNeighborsClassifier(n_neighbors=5)
evaluate_model("KNN", knn_model, X_train, y_train, X_valid, y_valid, X_test, y_test)


Training KNN model...

Validation Performance of KNN:
[[ 0  0  2  0  0  0  0  0  0  0]
 [ 0  0  6  3  0  0  0  0  0  0]
 [ 0  0  5  0  0  0  0  0  0  0]
 [ 0  0  1  1  0  0  0  0  0  0]
 [ 0  1  2  1  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0]
 [ 0  3  3  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  2  1  0]
 [ 0  0 25 26  0  0  0  0 10  0]
 [ 0  0  7  0  0  0  0  0  0  0]]
              precision    recall  f1-score   support

      Ajwain       0.00      0.00      0.00         2
      Almond       0.00      0.00      0.00         9
      Ashoka       0.09      1.00      0.17         5
   DrumStick       0.03      0.50      0.06         2
    Fittonia       0.00      0.00      0.00         4
    Hibiscus       0.00      0.00      0.00         3
   JackFruit       0.00      0.00      0.00         8
       Mango       1.00      0.67      0.80         3
        Neem       0.77      0.16      0.27        61
     Parijat       0.00      0.00      0.00         7

    accuracy      

e:\!VNIT College\A. Pattern Recognition\Leaf\venv\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
e:\!VNIT College\A. Pattern Recognition\Leaf\venv\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
e:\!VNIT College\A. Pattern Recognition\Leaf\venv\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metr

### 4. Random Forest 

In [12]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
evaluate_model("Random Forest", rf_model, X_train, y_train, X_valid, y_valid, X_test, y_test)


Training Random Forest model...

Validation Performance of Random Forest:
[[ 1  0  0  0  0  0  0  1  0  0]
 [ 0  2  0  0  0  0  0  3  4  0]
 [ 0  2  0  0  0  0  0  2  1  0]
 [ 0  1  0  0  0  0  0  0  1  0]
 [ 0  1  0  0  0  0  0  0  3  0]
 [ 0  0  0  0  0  1  0  1  1  0]
 [ 0  3  0  0  0  0  0  5  0  0]
 [ 0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  3  0  0  0  1 57  0]
 [ 0  4  1  0  0  0  0  2  0  0]]
              precision    recall  f1-score   support

      Ajwain       1.00      0.50      0.67         2
      Almond       0.15      0.22      0.18         9
      Ashoka       0.00      0.00      0.00         5
   DrumStick       0.00      0.00      0.00         2
    Fittonia       0.00      0.00      0.00         4
    Hibiscus       1.00      0.33      0.50         3
   JackFruit       0.00      0.00      0.00         8
       Mango       0.17      1.00      0.29         3
        Neem       0.85      0.93      0.89        61
     Parijat       0.00      0.00      0.00         7

e:\!VNIT College\A. Pattern Recognition\Leaf\venv\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
e:\!VNIT College\A. Pattern Recognition\Leaf\venv\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
e:\!VNIT College\A. Pattern Recognition\Leaf\venv\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metr